# Generated by Django 5.1.1 on 2024-09-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_groceryitem_created_at_groceryitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
